modLoader="kotlinforforge"
loaderVersion="[5.12,)"
license="MIT"

[[mods]]
modId="hexxysable"
version="${version}"
displayName="HexxySable"
logoFile="icon.png"
authors="TechTastic; HexxySable NeoForge port"
description='''Hex Casting navimancy actions ported to NeoForge 1.21.1 and adapted to Sable sub-level physics.'''

[[mixins]]
config="hexxysable.mixins.json"

[[mixins]]
config="hexxysable-moreiotas.mixins.json"
requiredMods=["moreiotas"]

[[mixins]]
config="hexxysable-hexical.mixins.json"
requiredMods=["hexical"]

[[dependencies.hexxysable]]
modId="neoforge"
type="required"
versionRange="[21.1.228,)"
ordering="NONE"
side="BOTH"

[[dependencies.hexxysable]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.hexxysable]]
modId="hexcasting"
type="required"
versionRange="[0.12.0-devel-pre-39,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexxysable]]
modId="sable"
type="required"
versionRange="[2.0.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexxysable]]
modId="sablecompanion"
type="required"
versionRange="[1.6.0,1.6.1)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexxysable]]
modId="patchouli"
type="optional"
versionRange="[1.21.1-93-NEOFORGE,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexxysable]]
modId="moreiotas"
type="optional"
versionRange="[0.1.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexxysable]]
modId="hexical"
type="optional"
versionRange="[2.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexxysable]]
modId="hexal"
type="optional"
versionRange="[0.3.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.hexxysable]]
modId="kotlinforforge"
type="required"
versionRange="[5.12,)"
ordering="NONE"
side="BOTH"
